// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Microsoft.EntityFrameworkCore.Migrations;

#pragma warning disable 219, 612, 618
#nullable disable

namespace proyecto_final.RestauranteSaborCasero.Data.CompiledModels
{
    public partial class ApplicationDbContextModel
    {
        partial void Initialize()
        {
            var compra = CompraEntityType.Create(this);
            var detalleCompra = DetalleCompraEntityType.Create(this);
            var detallePedido = DetallePedidoEntityType.Create(this);
            var ingrediente = IngredienteEntityType.Create(this);
            var inventario = InventarioEntityType.Create(this);
            var mesa = MesaEntityType.Create(this);
            var pedido = PedidoEntityType.Create(this);
            var plato = PlatoEntityType.Create(this);
            var platoIngrediente = PlatoIngredienteEntityType.Create(this);
            var usuario = UsuarioEntityType.Create(this);

            CompraEntityType.CreateForeignKey1(compra, usuario);
            DetalleCompraEntityType.CreateForeignKey1(detalleCompra, compra);
            DetalleCompraEntityType.CreateForeignKey2(detalleCompra, ingrediente);
            DetallePedidoEntityType.CreateForeignKey1(detallePedido, pedido);
            DetallePedidoEntityType.CreateForeignKey2(detallePedido, plato);
            InventarioEntityType.CreateForeignKey1(inventario, ingrediente);
            PedidoEntityType.CreateForeignKey1(pedido, mesa);
            PedidoEntityType.CreateForeignKey2(pedido, usuario);
            PlatoIngredienteEntityType.CreateForeignKey1(platoIngrediente, ingrediente);
            PlatoIngredienteEntityType.CreateForeignKey2(platoIngrediente, plato);

            CompraEntityType.CreateAnnotations(compra);
            DetalleCompraEntityType.CreateAnnotations(detalleCompra);
            DetallePedidoEntityType.CreateAnnotations(detallePedido);
            IngredienteEntityType.CreateAnnotations(ingrediente);
            InventarioEntityType.CreateAnnotations(inventario);
            MesaEntityType.CreateAnnotations(mesa);
            PedidoEntityType.CreateAnnotations(pedido);
            PlatoEntityType.CreateAnnotations(plato);
            PlatoIngredienteEntityType.CreateAnnotations(platoIngrediente);
            UsuarioEntityType.CreateAnnotations(usuario);

            AddAnnotation("ProductVersion", "8.0.11");
            AddAnnotation("Relational:MaxIdentifierLength", 64);
            AddRuntimeAnnotation("Relational:RelationalModel", CreateRelationalModel());
        }

        private IRelationalModel CreateRelationalModel()
        {
            var relationalModel = new RelationalModel(this);

            var compra = FindEntityType("RestauranteSaborCasero.Models.Compra")!;

            var defaultTableMappings = new List<TableMappingBase<ColumnMappingBase>>();
            compra.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings);
            var restauranteSaborCaseroModelsCompraTableBase = new TableBase("RestauranteSaborCasero.Models.Compra", null, relationalModel);
            var fechaColumnBase = new ColumnBase<ColumnMappingBase>("Fecha", "datetime(6)", restauranteSaborCaseroModelsCompraTableBase);
            restauranteSaborCaseroModelsCompraTableBase.Columns.Add("Fecha", fechaColumnBase);
            var idCompraColumnBase = new ColumnBase<ColumnMappingBase>("IdCompra", "int", restauranteSaborCaseroModelsCompraTableBase);
            restauranteSaborCaseroModelsCompraTableBase.Columns.Add("IdCompra", idCompraColumnBase);
            var idUsuarioColumnBase = new ColumnBase<ColumnMappingBase>("IdUsuario", "int", restauranteSaborCaseroModelsCompraTableBase);
            restauranteSaborCaseroModelsCompraTableBase.Columns.Add("IdUsuario", idUsuarioColumnBase);
            var proveedorColumnBase = new ColumnBase<ColumnMappingBase>("Proveedor", "varchar(150)", restauranteSaborCaseroModelsCompraTableBase);
            restauranteSaborCaseroModelsCompraTableBase.Columns.Add("Proveedor", proveedorColumnBase);
            relationalModel.DefaultTables.Add("RestauranteSaborCasero.Models.Compra", restauranteSaborCaseroModelsCompraTableBase);
            var restauranteSaborCaseroModelsCompraMappingBase = new TableMappingBase<ColumnMappingBase>(compra, restauranteSaborCaseroModelsCompraTableBase, true);
            restauranteSaborCaseroModelsCompraTableBase.AddTypeMapping(restauranteSaborCaseroModelsCompraMappingBase, false);
            defaultTableMappings.Add(restauranteSaborCaseroModelsCompraMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idCompraColumnBase, compra.FindProperty("IdCompra")!, restauranteSaborCaseroModelsCompraMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fechaColumnBase, compra.FindProperty("Fecha")!, restauranteSaborCaseroModelsCompraMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idUsuarioColumnBase, compra.FindProperty("IdUsuario")!, restauranteSaborCaseroModelsCompraMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)proveedorColumnBase, compra.FindProperty("Proveedor")!, restauranteSaborCaseroModelsCompraMappingBase);

            var tableMappings = new List<TableMapping>();
            compra.SetRuntimeAnnotation("Relational:TableMappings", tableMappings);
            var comprasTable = new Table("Compras", null, relationalModel);
            var idCompraColumn = new Column("IdCompra", "int", comprasTable);
            comprasTable.Columns.Add("IdCompra", idCompraColumn);
            idCompraColumn.AddAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
            var fechaColumn = new Column("Fecha", "datetime(6)", comprasTable);
            comprasTable.Columns.Add("Fecha", fechaColumn);
            var idUsuarioColumn = new Column("IdUsuario", "int", comprasTable);
            comprasTable.Columns.Add("IdUsuario", idUsuarioColumn);
            var proveedorColumn = new Column("Proveedor", "varchar(150)", comprasTable);
            comprasTable.Columns.Add("Proveedor", proveedorColumn);
            proveedorColumn.AddAnnotation("MySql:CharSet", "utf8mb4");
            var pK_Compras = new UniqueConstraint("PK_Compras", comprasTable, new[] { idCompraColumn });
            comprasTable.PrimaryKey = pK_Compras;
            var pK_ComprasUc = RelationalModel.GetKey(this,
                "RestauranteSaborCasero.Models.Compra",
                new[] { "IdCompra" });
            pK_Compras.MappedKeys.Add(pK_ComprasUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_ComprasUc).Add(pK_Compras);
            comprasTable.UniqueConstraints.Add("PK_Compras", pK_Compras);
            var iX_Compras_IdUsuario = new TableIndex(
            "IX_Compras_IdUsuario", comprasTable, new[] { idUsuarioColumn }, false);
            var iX_Compras_IdUsuarioIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.Compra",
                new[] { "IdUsuario" });
            iX_Compras_IdUsuario.MappedIndexes.Add(iX_Compras_IdUsuarioIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Compras_IdUsuarioIx).Add(iX_Compras_IdUsuario);
            comprasTable.Indexes.Add("IX_Compras_IdUsuario", iX_Compras_IdUsuario);
            comprasTable.AddAnnotation("MySql:CharSet", "utf8mb4");
            relationalModel.Tables.Add(("Compras", null), comprasTable);
            var comprasTableMapping = new TableMapping(compra, comprasTable, true);
            comprasTable.AddTypeMapping(comprasTableMapping, false);
            tableMappings.Add(comprasTableMapping);
            RelationalModel.CreateColumnMapping(idCompraColumn, compra.FindProperty("IdCompra")!, comprasTableMapping);
            RelationalModel.CreateColumnMapping(fechaColumn, compra.FindProperty("Fecha")!, comprasTableMapping);
            RelationalModel.CreateColumnMapping(idUsuarioColumn, compra.FindProperty("IdUsuario")!, comprasTableMapping);
            RelationalModel.CreateColumnMapping(proveedorColumn, compra.FindProperty("Proveedor")!, comprasTableMapping);

            var detalleCompra = FindEntityType("RestauranteSaborCasero.Models.DetalleCompra")!;

            var defaultTableMappings0 = new List<TableMappingBase<ColumnMappingBase>>();
            detalleCompra.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings0);
            var restauranteSaborCaseroModelsDetalleCompraTableBase = new TableBase("RestauranteSaborCasero.Models.DetalleCompra", null, relationalModel);
            var cantidadColumnBase = new ColumnBase<ColumnMappingBase>("Cantidad", "decimal(10,2)", restauranteSaborCaseroModelsDetalleCompraTableBase);
            restauranteSaborCaseroModelsDetalleCompraTableBase.Columns.Add("Cantidad", cantidadColumnBase);
            var idCompraColumnBase0 = new ColumnBase<ColumnMappingBase>("IdCompra", "int", restauranteSaborCaseroModelsDetalleCompraTableBase);
            restauranteSaborCaseroModelsDetalleCompraTableBase.Columns.Add("IdCompra", idCompraColumnBase0);
            var idDetalleCompraColumnBase = new ColumnBase<ColumnMappingBase>("IdDetalleCompra", "int", restauranteSaborCaseroModelsDetalleCompraTableBase);
            restauranteSaborCaseroModelsDetalleCompraTableBase.Columns.Add("IdDetalleCompra", idDetalleCompraColumnBase);
            var idIngredienteColumnBase = new ColumnBase<ColumnMappingBase>("IdIngrediente", "int", restauranteSaborCaseroModelsDetalleCompraTableBase);
            restauranteSaborCaseroModelsDetalleCompraTableBase.Columns.Add("IdIngrediente", idIngredienteColumnBase);
            relationalModel.DefaultTables.Add("RestauranteSaborCasero.Models.DetalleCompra", restauranteSaborCaseroModelsDetalleCompraTableBase);
            var restauranteSaborCaseroModelsDetalleCompraMappingBase = new TableMappingBase<ColumnMappingBase>(detalleCompra, restauranteSaborCaseroModelsDetalleCompraTableBase, true);
            restauranteSaborCaseroModelsDetalleCompraTableBase.AddTypeMapping(restauranteSaborCaseroModelsDetalleCompraMappingBase, false);
            defaultTableMappings0.Add(restauranteSaborCaseroModelsDetalleCompraMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idDetalleCompraColumnBase, detalleCompra.FindProperty("IdDetalleCompra")!, restauranteSaborCaseroModelsDetalleCompraMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cantidadColumnBase, detalleCompra.FindProperty("Cantidad")!, restauranteSaborCaseroModelsDetalleCompraMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idCompraColumnBase0, detalleCompra.FindProperty("IdCompra")!, restauranteSaborCaseroModelsDetalleCompraMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idIngredienteColumnBase, detalleCompra.FindProperty("IdIngrediente")!, restauranteSaborCaseroModelsDetalleCompraMappingBase);

            var tableMappings0 = new List<TableMapping>();
            detalleCompra.SetRuntimeAnnotation("Relational:TableMappings", tableMappings0);
            var detalleComprasTable = new Table("DetalleCompras", null, relationalModel);
            var idDetalleCompraColumn = new Column("IdDetalleCompra", "int", detalleComprasTable);
            detalleComprasTable.Columns.Add("IdDetalleCompra", idDetalleCompraColumn);
            idDetalleCompraColumn.AddAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
            var cantidadColumn = new Column("Cantidad", "decimal(10,2)", detalleComprasTable);
            detalleComprasTable.Columns.Add("Cantidad", cantidadColumn);
            var idCompraColumn0 = new Column("IdCompra", "int", detalleComprasTable);
            detalleComprasTable.Columns.Add("IdCompra", idCompraColumn0);
            var idIngredienteColumn = new Column("IdIngrediente", "int", detalleComprasTable);
            detalleComprasTable.Columns.Add("IdIngrediente", idIngredienteColumn);
            var pK_DetalleCompras = new UniqueConstraint("PK_DetalleCompras", detalleComprasTable, new[] { idDetalleCompraColumn });
            detalleComprasTable.PrimaryKey = pK_DetalleCompras;
            var pK_DetalleComprasUc = RelationalModel.GetKey(this,
                "RestauranteSaborCasero.Models.DetalleCompra",
                new[] { "IdDetalleCompra" });
            pK_DetalleCompras.MappedKeys.Add(pK_DetalleComprasUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_DetalleComprasUc).Add(pK_DetalleCompras);
            detalleComprasTable.UniqueConstraints.Add("PK_DetalleCompras", pK_DetalleCompras);
            var iX_DetalleCompras_IdCompra = new TableIndex(
            "IX_DetalleCompras_IdCompra", detalleComprasTable, new[] { idCompraColumn0 }, false);
            var iX_DetalleCompras_IdCompraIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.DetalleCompra",
                new[] { "IdCompra" });
            iX_DetalleCompras_IdCompra.MappedIndexes.Add(iX_DetalleCompras_IdCompraIx);
            RelationalModel.GetOrCreateTableIndexes(iX_DetalleCompras_IdCompraIx).Add(iX_DetalleCompras_IdCompra);
            detalleComprasTable.Indexes.Add("IX_DetalleCompras_IdCompra", iX_DetalleCompras_IdCompra);
            var iX_DetalleCompras_IdIngrediente = new TableIndex(
            "IX_DetalleCompras_IdIngrediente", detalleComprasTable, new[] { idIngredienteColumn }, false);
            var iX_DetalleCompras_IdIngredienteIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.DetalleCompra",
                new[] { "IdIngrediente" });
            iX_DetalleCompras_IdIngrediente.MappedIndexes.Add(iX_DetalleCompras_IdIngredienteIx);
            RelationalModel.GetOrCreateTableIndexes(iX_DetalleCompras_IdIngredienteIx).Add(iX_DetalleCompras_IdIngrediente);
            detalleComprasTable.Indexes.Add("IX_DetalleCompras_IdIngrediente", iX_DetalleCompras_IdIngrediente);
            detalleComprasTable.AddAnnotation("MySql:CharSet", "utf8mb4");
            relationalModel.Tables.Add(("DetalleCompras", null), detalleComprasTable);
            var detalleComprasTableMapping = new TableMapping(detalleCompra, detalleComprasTable, true);
            detalleComprasTable.AddTypeMapping(detalleComprasTableMapping, false);
            tableMappings0.Add(detalleComprasTableMapping);
            RelationalModel.CreateColumnMapping(idDetalleCompraColumn, detalleCompra.FindProperty("IdDetalleCompra")!, detalleComprasTableMapping);
            RelationalModel.CreateColumnMapping(cantidadColumn, detalleCompra.FindProperty("Cantidad")!, detalleComprasTableMapping);
            RelationalModel.CreateColumnMapping(idCompraColumn0, detalleCompra.FindProperty("IdCompra")!, detalleComprasTableMapping);
            RelationalModel.CreateColumnMapping(idIngredienteColumn, detalleCompra.FindProperty("IdIngrediente")!, detalleComprasTableMapping);

            var detallePedido = FindEntityType("RestauranteSaborCasero.Models.DetallePedido")!;

            var defaultTableMappings1 = new List<TableMappingBase<ColumnMappingBase>>();
            detallePedido.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings1);
            var restauranteSaborCaseroModelsDetallePedidoTableBase = new TableBase("RestauranteSaborCasero.Models.DetallePedido", null, relationalModel);
            var cantidadColumnBase0 = new ColumnBase<ColumnMappingBase>("Cantidad", "int", restauranteSaborCaseroModelsDetallePedidoTableBase);
            restauranteSaborCaseroModelsDetallePedidoTableBase.Columns.Add("Cantidad", cantidadColumnBase0);
            var idDetalleColumnBase = new ColumnBase<ColumnMappingBase>("IdDetalle", "int", restauranteSaborCaseroModelsDetallePedidoTableBase);
            restauranteSaborCaseroModelsDetallePedidoTableBase.Columns.Add("IdDetalle", idDetalleColumnBase);
            var idPedidoColumnBase = new ColumnBase<ColumnMappingBase>("IdPedido", "int", restauranteSaborCaseroModelsDetallePedidoTableBase);
            restauranteSaborCaseroModelsDetallePedidoTableBase.Columns.Add("IdPedido", idPedidoColumnBase);
            var idPlatoColumnBase = new ColumnBase<ColumnMappingBase>("IdPlato", "int", restauranteSaborCaseroModelsDetallePedidoTableBase);
            restauranteSaborCaseroModelsDetallePedidoTableBase.Columns.Add("IdPlato", idPlatoColumnBase);
            var indicacionesExtraColumnBase = new ColumnBase<ColumnMappingBase>("IndicacionesExtra", "varchar(255)", restauranteSaborCaseroModelsDetallePedidoTableBase)
            {
                IsNullable = true
            };
            restauranteSaborCaseroModelsDetallePedidoTableBase.Columns.Add("IndicacionesExtra", indicacionesExtraColumnBase);
            relationalModel.DefaultTables.Add("RestauranteSaborCasero.Models.DetallePedido", restauranteSaborCaseroModelsDetallePedidoTableBase);
            var restauranteSaborCaseroModelsDetallePedidoMappingBase = new TableMappingBase<ColumnMappingBase>(detallePedido, restauranteSaborCaseroModelsDetallePedidoTableBase, true);
            restauranteSaborCaseroModelsDetallePedidoTableBase.AddTypeMapping(restauranteSaborCaseroModelsDetallePedidoMappingBase, false);
            defaultTableMappings1.Add(restauranteSaborCaseroModelsDetallePedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idDetalleColumnBase, detallePedido.FindProperty("IdDetalle")!, restauranteSaborCaseroModelsDetallePedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cantidadColumnBase0, detallePedido.FindProperty("Cantidad")!, restauranteSaborCaseroModelsDetallePedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idPedidoColumnBase, detallePedido.FindProperty("IdPedido")!, restauranteSaborCaseroModelsDetallePedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idPlatoColumnBase, detallePedido.FindProperty("IdPlato")!, restauranteSaborCaseroModelsDetallePedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)indicacionesExtraColumnBase, detallePedido.FindProperty("IndicacionesExtra")!, restauranteSaborCaseroModelsDetallePedidoMappingBase);

            var tableMappings1 = new List<TableMapping>();
            detallePedido.SetRuntimeAnnotation("Relational:TableMappings", tableMappings1);
            var detallePedidosTable = new Table("DetallePedidos", null, relationalModel);
            var idDetalleColumn = new Column("IdDetalle", "int", detallePedidosTable);
            detallePedidosTable.Columns.Add("IdDetalle", idDetalleColumn);
            idDetalleColumn.AddAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
            var cantidadColumn0 = new Column("Cantidad", "int", detallePedidosTable);
            detallePedidosTable.Columns.Add("Cantidad", cantidadColumn0);
            var idPedidoColumn = new Column("IdPedido", "int", detallePedidosTable);
            detallePedidosTable.Columns.Add("IdPedido", idPedidoColumn);
            var idPlatoColumn = new Column("IdPlato", "int", detallePedidosTable);
            detallePedidosTable.Columns.Add("IdPlato", idPlatoColumn);
            var indicacionesExtraColumn = new Column("IndicacionesExtra", "varchar(255)", detallePedidosTable)
            {
                IsNullable = true
            };
            detallePedidosTable.Columns.Add("IndicacionesExtra", indicacionesExtraColumn);
            indicacionesExtraColumn.AddAnnotation("MySql:CharSet", "utf8mb4");
            var pK_DetallePedidos = new UniqueConstraint("PK_DetallePedidos", detallePedidosTable, new[] { idDetalleColumn });
            detallePedidosTable.PrimaryKey = pK_DetallePedidos;
            var pK_DetallePedidosUc = RelationalModel.GetKey(this,
                "RestauranteSaborCasero.Models.DetallePedido",
                new[] { "IdDetalle" });
            pK_DetallePedidos.MappedKeys.Add(pK_DetallePedidosUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_DetallePedidosUc).Add(pK_DetallePedidos);
            detallePedidosTable.UniqueConstraints.Add("PK_DetallePedidos", pK_DetallePedidos);
            var iX_DetallePedidos_IdPedido = new TableIndex(
            "IX_DetallePedidos_IdPedido", detallePedidosTable, new[] { idPedidoColumn }, false);
            var iX_DetallePedidos_IdPedidoIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.DetallePedido",
                new[] { "IdPedido" });
            iX_DetallePedidos_IdPedido.MappedIndexes.Add(iX_DetallePedidos_IdPedidoIx);
            RelationalModel.GetOrCreateTableIndexes(iX_DetallePedidos_IdPedidoIx).Add(iX_DetallePedidos_IdPedido);
            detallePedidosTable.Indexes.Add("IX_DetallePedidos_IdPedido", iX_DetallePedidos_IdPedido);
            var iX_DetallePedidos_IdPlato = new TableIndex(
            "IX_DetallePedidos_IdPlato", detallePedidosTable, new[] { idPlatoColumn }, false);
            var iX_DetallePedidos_IdPlatoIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.DetallePedido",
                new[] { "IdPlato" });
            iX_DetallePedidos_IdPlato.MappedIndexes.Add(iX_DetallePedidos_IdPlatoIx);
            RelationalModel.GetOrCreateTableIndexes(iX_DetallePedidos_IdPlatoIx).Add(iX_DetallePedidos_IdPlato);
            detallePedidosTable.Indexes.Add("IX_DetallePedidos_IdPlato", iX_DetallePedidos_IdPlato);
            detallePedidosTable.AddAnnotation("MySql:CharSet", "utf8mb4");
            relationalModel.Tables.Add(("DetallePedidos", null), detallePedidosTable);
            var detallePedidosTableMapping = new TableMapping(detallePedido, detallePedidosTable, true);
            detallePedidosTable.AddTypeMapping(detallePedidosTableMapping, false);
            tableMappings1.Add(detallePedidosTableMapping);
            RelationalModel.CreateColumnMapping(idDetalleColumn, detallePedido.FindProperty("IdDetalle")!, detallePedidosTableMapping);
            RelationalModel.CreateColumnMapping(cantidadColumn0, detallePedido.FindProperty("Cantidad")!, detallePedidosTableMapping);
            RelationalModel.CreateColumnMapping(idPedidoColumn, detallePedido.FindProperty("IdPedido")!, detallePedidosTableMapping);
            RelationalModel.CreateColumnMapping(idPlatoColumn, detallePedido.FindProperty("IdPlato")!, detallePedidosTableMapping);
            RelationalModel.CreateColumnMapping(indicacionesExtraColumn, detallePedido.FindProperty("IndicacionesExtra")!, detallePedidosTableMapping);

            var ingrediente = FindEntityType("RestauranteSaborCasero.Models.Ingrediente")!;

            var defaultTableMappings2 = new List<TableMappingBase<ColumnMappingBase>>();
            ingrediente.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings2);
            var restauranteSaborCaseroModelsIngredienteTableBase = new TableBase("RestauranteSaborCasero.Models.Ingrediente", null, relationalModel);
            var cantidadDisponibleColumnBase = new ColumnBase<ColumnMappingBase>("CantidadDisponible", "decimal(10,2)", restauranteSaborCaseroModelsIngredienteTableBase);
            restauranteSaborCaseroModelsIngredienteTableBase.Columns.Add("CantidadDisponible", cantidadDisponibleColumnBase);
            var cantidadMinimaColumnBase = new ColumnBase<ColumnMappingBase>("CantidadMinima", "decimal(10,2)", restauranteSaborCaseroModelsIngredienteTableBase);
            restauranteSaborCaseroModelsIngredienteTableBase.Columns.Add("CantidadMinima", cantidadMinimaColumnBase);
            var estadoColumnBase = new ColumnBase<ColumnMappingBase>("Estado", "int", restauranteSaborCaseroModelsIngredienteTableBase);
            restauranteSaborCaseroModelsIngredienteTableBase.Columns.Add("Estado", estadoColumnBase);
            var idIngredienteColumnBase0 = new ColumnBase<ColumnMappingBase>("IdIngrediente", "int", restauranteSaborCaseroModelsIngredienteTableBase);
            restauranteSaborCaseroModelsIngredienteTableBase.Columns.Add("IdIngrediente", idIngredienteColumnBase0);
            var nombreColumnBase = new ColumnBase<ColumnMappingBase>("Nombre", "varchar(100)", restauranteSaborCaseroModelsIngredienteTableBase);
            restauranteSaborCaseroModelsIngredienteTableBase.Columns.Add("Nombre", nombreColumnBase);
            var unidadMedidaColumnBase = new ColumnBase<ColumnMappingBase>("UnidadMedida", "varchar(30)", restauranteSaborCaseroModelsIngredienteTableBase);
            restauranteSaborCaseroModelsIngredienteTableBase.Columns.Add("UnidadMedida", unidadMedidaColumnBase);
            relationalModel.DefaultTables.Add("RestauranteSaborCasero.Models.Ingrediente", restauranteSaborCaseroModelsIngredienteTableBase);
            var restauranteSaborCaseroModelsIngredienteMappingBase = new TableMappingBase<ColumnMappingBase>(ingrediente, restauranteSaborCaseroModelsIngredienteTableBase, true);
            restauranteSaborCaseroModelsIngredienteTableBase.AddTypeMapping(restauranteSaborCaseroModelsIngredienteMappingBase, false);
            defaultTableMappings2.Add(restauranteSaborCaseroModelsIngredienteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idIngredienteColumnBase0, ingrediente.FindProperty("IdIngrediente")!, restauranteSaborCaseroModelsIngredienteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cantidadDisponibleColumnBase, ingrediente.FindProperty("CantidadDisponible")!, restauranteSaborCaseroModelsIngredienteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cantidadMinimaColumnBase, ingrediente.FindProperty("CantidadMinima")!, restauranteSaborCaseroModelsIngredienteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)estadoColumnBase, ingrediente.FindProperty("Estado")!, restauranteSaborCaseroModelsIngredienteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nombreColumnBase, ingrediente.FindProperty("Nombre")!, restauranteSaborCaseroModelsIngredienteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)unidadMedidaColumnBase, ingrediente.FindProperty("UnidadMedida")!, restauranteSaborCaseroModelsIngredienteMappingBase);

            var tableMappings2 = new List<TableMapping>();
            ingrediente.SetRuntimeAnnotation("Relational:TableMappings", tableMappings2);
            var ingredientesTable = new Table("Ingredientes", null, relationalModel);
            var idIngredienteColumn0 = new Column("IdIngrediente", "int", ingredientesTable);
            ingredientesTable.Columns.Add("IdIngrediente", idIngredienteColumn0);
            idIngredienteColumn0.AddAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
            var cantidadDisponibleColumn = new Column("CantidadDisponible", "decimal(10,2)", ingredientesTable);
            ingredientesTable.Columns.Add("CantidadDisponible", cantidadDisponibleColumn);
            var cantidadMinimaColumn = new Column("CantidadMinima", "decimal(10,2)", ingredientesTable);
            ingredientesTable.Columns.Add("CantidadMinima", cantidadMinimaColumn);
            var estadoColumn = new Column("Estado", "int", ingredientesTable);
            ingredientesTable.Columns.Add("Estado", estadoColumn);
            var nombreColumn = new Column("Nombre", "varchar(100)", ingredientesTable);
            ingredientesTable.Columns.Add("Nombre", nombreColumn);
            nombreColumn.AddAnnotation("MySql:CharSet", "utf8mb4");
            var unidadMedidaColumn = new Column("UnidadMedida", "varchar(30)", ingredientesTable);
            ingredientesTable.Columns.Add("UnidadMedida", unidadMedidaColumn);
            unidadMedidaColumn.AddAnnotation("MySql:CharSet", "utf8mb4");
            var pK_Ingredientes = new UniqueConstraint("PK_Ingredientes", ingredientesTable, new[] { idIngredienteColumn0 });
            ingredientesTable.PrimaryKey = pK_Ingredientes;
            var pK_IngredientesUc = RelationalModel.GetKey(this,
                "RestauranteSaborCasero.Models.Ingrediente",
                new[] { "IdIngrediente" });
            pK_Ingredientes.MappedKeys.Add(pK_IngredientesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_IngredientesUc).Add(pK_Ingredientes);
            ingredientesTable.UniqueConstraints.Add("PK_Ingredientes", pK_Ingredientes);
            ingredientesTable.AddAnnotation("MySql:CharSet", "utf8mb4");
            relationalModel.Tables.Add(("Ingredientes", null), ingredientesTable);
            var ingredientesTableMapping = new TableMapping(ingrediente, ingredientesTable, true);
            ingredientesTable.AddTypeMapping(ingredientesTableMapping, false);
            tableMappings2.Add(ingredientesTableMapping);
            RelationalModel.CreateColumnMapping(idIngredienteColumn0, ingrediente.FindProperty("IdIngrediente")!, ingredientesTableMapping);
            RelationalModel.CreateColumnMapping(cantidadDisponibleColumn, ingrediente.FindProperty("CantidadDisponible")!, ingredientesTableMapping);
            RelationalModel.CreateColumnMapping(cantidadMinimaColumn, ingrediente.FindProperty("CantidadMinima")!, ingredientesTableMapping);
            RelationalModel.CreateColumnMapping(estadoColumn, ingrediente.FindProperty("Estado")!, ingredientesTableMapping);
            RelationalModel.CreateColumnMapping(nombreColumn, ingrediente.FindProperty("Nombre")!, ingredientesTableMapping);
            RelationalModel.CreateColumnMapping(unidadMedidaColumn, ingrediente.FindProperty("UnidadMedida")!, ingredientesTableMapping);

            var inventario = FindEntityType("RestauranteSaborCasero.Models.Inventario")!;

            var defaultTableMappings3 = new List<TableMappingBase<ColumnMappingBase>>();
            inventario.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings3);
            var restauranteSaborCaseroModelsInventarioTableBase = new TableBase("RestauranteSaborCasero.Models.Inventario", null, relationalModel);
            var cantidadColumnBase1 = new ColumnBase<ColumnMappingBase>("Cantidad", "decimal(10,2)", restauranteSaborCaseroModelsInventarioTableBase);
            restauranteSaborCaseroModelsInventarioTableBase.Columns.Add("Cantidad", cantidadColumnBase1);
            var fechaColumnBase0 = new ColumnBase<ColumnMappingBase>("Fecha", "datetime(6)", restauranteSaborCaseroModelsInventarioTableBase);
            restauranteSaborCaseroModelsInventarioTableBase.Columns.Add("Fecha", fechaColumnBase0);
            var idIngredienteColumnBase1 = new ColumnBase<ColumnMappingBase>("IdIngrediente", "int", restauranteSaborCaseroModelsInventarioTableBase);
            restauranteSaborCaseroModelsInventarioTableBase.Columns.Add("IdIngrediente", idIngredienteColumnBase1);
            var idInventarioColumnBase = new ColumnBase<ColumnMappingBase>("IdInventario", "int", restauranteSaborCaseroModelsInventarioTableBase);
            restauranteSaborCaseroModelsInventarioTableBase.Columns.Add("IdInventario", idInventarioColumnBase);
            var motivoColumnBase = new ColumnBase<ColumnMappingBase>("Motivo", "varchar(255)", restauranteSaborCaseroModelsInventarioTableBase)
            {
                IsNullable = true
            };
            restauranteSaborCaseroModelsInventarioTableBase.Columns.Add("Motivo", motivoColumnBase);
            var tipoMovimientoColumnBase = new ColumnBase<ColumnMappingBase>("TipoMovimiento", "int", restauranteSaborCaseroModelsInventarioTableBase);
            restauranteSaborCaseroModelsInventarioTableBase.Columns.Add("TipoMovimiento", tipoMovimientoColumnBase);
            relationalModel.DefaultTables.Add("RestauranteSaborCasero.Models.Inventario", restauranteSaborCaseroModelsInventarioTableBase);
            var restauranteSaborCaseroModelsInventarioMappingBase = new TableMappingBase<ColumnMappingBase>(inventario, restauranteSaborCaseroModelsInventarioTableBase, true);
            restauranteSaborCaseroModelsInventarioTableBase.AddTypeMapping(restauranteSaborCaseroModelsInventarioMappingBase, false);
            defaultTableMappings3.Add(restauranteSaborCaseroModelsInventarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idInventarioColumnBase, inventario.FindProperty("IdInventario")!, restauranteSaborCaseroModelsInventarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cantidadColumnBase1, inventario.FindProperty("Cantidad")!, restauranteSaborCaseroModelsInventarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fechaColumnBase0, inventario.FindProperty("Fecha")!, restauranteSaborCaseroModelsInventarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idIngredienteColumnBase1, inventario.FindProperty("IdIngrediente")!, restauranteSaborCaseroModelsInventarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)motivoColumnBase, inventario.FindProperty("Motivo")!, restauranteSaborCaseroModelsInventarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tipoMovimientoColumnBase, inventario.FindProperty("TipoMovimiento")!, restauranteSaborCaseroModelsInventarioMappingBase);

            var tableMappings3 = new List<TableMapping>();
            inventario.SetRuntimeAnnotation("Relational:TableMappings", tableMappings3);
            var inventariosTable = new Table("Inventarios", null, relationalModel);
            var idInventarioColumn = new Column("IdInventario", "int", inventariosTable);
            inventariosTable.Columns.Add("IdInventario", idInventarioColumn);
            idInventarioColumn.AddAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
            var cantidadColumn1 = new Column("Cantidad", "decimal(10,2)", inventariosTable);
            inventariosTable.Columns.Add("Cantidad", cantidadColumn1);
            var fechaColumn0 = new Column("Fecha", "datetime(6)", inventariosTable);
            inventariosTable.Columns.Add("Fecha", fechaColumn0);
            var idIngredienteColumn1 = new Column("IdIngrediente", "int", inventariosTable);
            inventariosTable.Columns.Add("IdIngrediente", idIngredienteColumn1);
            var motivoColumn = new Column("Motivo", "varchar(255)", inventariosTable)
            {
                IsNullable = true
            };
            inventariosTable.Columns.Add("Motivo", motivoColumn);
            motivoColumn.AddAnnotation("MySql:CharSet", "utf8mb4");
            var tipoMovimientoColumn = new Column("TipoMovimiento", "int", inventariosTable);
            inventariosTable.Columns.Add("TipoMovimiento", tipoMovimientoColumn);
            var pK_Inventarios = new UniqueConstraint("PK_Inventarios", inventariosTable, new[] { idInventarioColumn });
            inventariosTable.PrimaryKey = pK_Inventarios;
            var pK_InventariosUc = RelationalModel.GetKey(this,
                "RestauranteSaborCasero.Models.Inventario",
                new[] { "IdInventario" });
            pK_Inventarios.MappedKeys.Add(pK_InventariosUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_InventariosUc).Add(pK_Inventarios);
            inventariosTable.UniqueConstraints.Add("PK_Inventarios", pK_Inventarios);
            var iX_Inventarios_IdIngrediente = new TableIndex(
            "IX_Inventarios_IdIngrediente", inventariosTable, new[] { idIngredienteColumn1 }, false);
            var iX_Inventarios_IdIngredienteIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.Inventario",
                new[] { "IdIngrediente" });
            iX_Inventarios_IdIngrediente.MappedIndexes.Add(iX_Inventarios_IdIngredienteIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Inventarios_IdIngredienteIx).Add(iX_Inventarios_IdIngrediente);
            inventariosTable.Indexes.Add("IX_Inventarios_IdIngrediente", iX_Inventarios_IdIngrediente);
            inventariosTable.AddAnnotation("MySql:CharSet", "utf8mb4");
            relationalModel.Tables.Add(("Inventarios", null), inventariosTable);
            var inventariosTableMapping = new TableMapping(inventario, inventariosTable, true);
            inventariosTable.AddTypeMapping(inventariosTableMapping, false);
            tableMappings3.Add(inventariosTableMapping);
            RelationalModel.CreateColumnMapping(idInventarioColumn, inventario.FindProperty("IdInventario")!, inventariosTableMapping);
            RelationalModel.CreateColumnMapping(cantidadColumn1, inventario.FindProperty("Cantidad")!, inventariosTableMapping);
            RelationalModel.CreateColumnMapping(fechaColumn0, inventario.FindProperty("Fecha")!, inventariosTableMapping);
            RelationalModel.CreateColumnMapping(idIngredienteColumn1, inventario.FindProperty("IdIngrediente")!, inventariosTableMapping);
            RelationalModel.CreateColumnMapping(motivoColumn, inventario.FindProperty("Motivo")!, inventariosTableMapping);
            RelationalModel.CreateColumnMapping(tipoMovimientoColumn, inventario.FindProperty("TipoMovimiento")!, inventariosTableMapping);

            var mesa = FindEntityType("RestauranteSaborCasero.Models.Mesa")!;

            var defaultTableMappings4 = new List<TableMappingBase<ColumnMappingBase>>();
            mesa.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings4);
            var restauranteSaborCaseroModelsMesaTableBase = new TableBase("RestauranteSaborCasero.Models.Mesa", null, relationalModel);
            var estadoColumnBase0 = new ColumnBase<ColumnMappingBase>("Estado", "int", restauranteSaborCaseroModelsMesaTableBase);
            restauranteSaborCaseroModelsMesaTableBase.Columns.Add("Estado", estadoColumnBase0);
            var idMesaColumnBase = new ColumnBase<ColumnMappingBase>("IdMesa", "int", restauranteSaborCaseroModelsMesaTableBase);
            restauranteSaborCaseroModelsMesaTableBase.Columns.Add("IdMesa", idMesaColumnBase);
            var numeroMesaColumnBase = new ColumnBase<ColumnMappingBase>("NumeroMesa", "int", restauranteSaborCaseroModelsMesaTableBase);
            restauranteSaborCaseroModelsMesaTableBase.Columns.Add("NumeroMesa", numeroMesaColumnBase);
            relationalModel.DefaultTables.Add("RestauranteSaborCasero.Models.Mesa", restauranteSaborCaseroModelsMesaTableBase);
            var restauranteSaborCaseroModelsMesaMappingBase = new TableMappingBase<ColumnMappingBase>(mesa, restauranteSaborCaseroModelsMesaTableBase, true);
            restauranteSaborCaseroModelsMesaTableBase.AddTypeMapping(restauranteSaborCaseroModelsMesaMappingBase, false);
            defaultTableMappings4.Add(restauranteSaborCaseroModelsMesaMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idMesaColumnBase, mesa.FindProperty("IdMesa")!, restauranteSaborCaseroModelsMesaMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)estadoColumnBase0, mesa.FindProperty("Estado")!, restauranteSaborCaseroModelsMesaMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)numeroMesaColumnBase, mesa.FindProperty("NumeroMesa")!, restauranteSaborCaseroModelsMesaMappingBase);

            var tableMappings4 = new List<TableMapping>();
            mesa.SetRuntimeAnnotation("Relational:TableMappings", tableMappings4);
            var mesasTable = new Table("Mesas", null, relationalModel);
            var idMesaColumn = new Column("IdMesa", "int", mesasTable);
            mesasTable.Columns.Add("IdMesa", idMesaColumn);
            idMesaColumn.AddAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
            var estadoColumn0 = new Column("Estado", "int", mesasTable);
            mesasTable.Columns.Add("Estado", estadoColumn0);
            var numeroMesaColumn = new Column("NumeroMesa", "int", mesasTable);
            mesasTable.Columns.Add("NumeroMesa", numeroMesaColumn);
            var pK_Mesas = new UniqueConstraint("PK_Mesas", mesasTable, new[] { idMesaColumn });
            mesasTable.PrimaryKey = pK_Mesas;
            var pK_MesasUc = RelationalModel.GetKey(this,
                "RestauranteSaborCasero.Models.Mesa",
                new[] { "IdMesa" });
            pK_Mesas.MappedKeys.Add(pK_MesasUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_MesasUc).Add(pK_Mesas);
            mesasTable.UniqueConstraints.Add("PK_Mesas", pK_Mesas);
            var iX_Mesas_NumeroMesa = new TableIndex(
            "IX_Mesas_NumeroMesa", mesasTable, new[] { numeroMesaColumn }, true);
            var iX_Mesas_NumeroMesaIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.Mesa",
                new[] { "NumeroMesa" });
            iX_Mesas_NumeroMesa.MappedIndexes.Add(iX_Mesas_NumeroMesaIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Mesas_NumeroMesaIx).Add(iX_Mesas_NumeroMesa);
            mesasTable.Indexes.Add("IX_Mesas_NumeroMesa", iX_Mesas_NumeroMesa);
            mesasTable.AddAnnotation("MySql:CharSet", "utf8mb4");
            relationalModel.Tables.Add(("Mesas", null), mesasTable);
            var mesasTableMapping = new TableMapping(mesa, mesasTable, true);
            mesasTable.AddTypeMapping(mesasTableMapping, false);
            tableMappings4.Add(mesasTableMapping);
            RelationalModel.CreateColumnMapping(idMesaColumn, mesa.FindProperty("IdMesa")!, mesasTableMapping);
            RelationalModel.CreateColumnMapping(estadoColumn0, mesa.FindProperty("Estado")!, mesasTableMapping);
            RelationalModel.CreateColumnMapping(numeroMesaColumn, mesa.FindProperty("NumeroMesa")!, mesasTableMapping);

            var pedido = FindEntityType("RestauranteSaborCasero.Models.Pedido")!;

            var defaultTableMappings5 = new List<TableMappingBase<ColumnMappingBase>>();
            pedido.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings5);
            var restauranteSaborCaseroModelsPedidoTableBase = new TableBase("RestauranteSaborCasero.Models.Pedido", null, relationalModel);
            var estadoColumnBase1 = new ColumnBase<ColumnMappingBase>("Estado", "int", restauranteSaborCaseroModelsPedidoTableBase);
            restauranteSaborCaseroModelsPedidoTableBase.Columns.Add("Estado", estadoColumnBase1);
            var fechaColumnBase1 = new ColumnBase<ColumnMappingBase>("Fecha", "datetime(6)", restauranteSaborCaseroModelsPedidoTableBase);
            restauranteSaborCaseroModelsPedidoTableBase.Columns.Add("Fecha", fechaColumnBase1);
            var horaFinColumnBase = new ColumnBase<ColumnMappingBase>("HoraFin", "time(6)", restauranteSaborCaseroModelsPedidoTableBase)
            {
                IsNullable = true
            };
            restauranteSaborCaseroModelsPedidoTableBase.Columns.Add("HoraFin", horaFinColumnBase);
            var horaInicioColumnBase = new ColumnBase<ColumnMappingBase>("HoraInicio", "time(6)", restauranteSaborCaseroModelsPedidoTableBase);
            restauranteSaborCaseroModelsPedidoTableBase.Columns.Add("HoraInicio", horaInicioColumnBase);
            var idMesaColumnBase0 = new ColumnBase<ColumnMappingBase>("IdMesa", "int", restauranteSaborCaseroModelsPedidoTableBase)
            {
                IsNullable = true
            };
            restauranteSaborCaseroModelsPedidoTableBase.Columns.Add("IdMesa", idMesaColumnBase0);
            var idMeseroColumnBase = new ColumnBase<ColumnMappingBase>("IdMesero", "int", restauranteSaborCaseroModelsPedidoTableBase);
            restauranteSaborCaseroModelsPedidoTableBase.Columns.Add("IdMesero", idMeseroColumnBase);
            var idPedidoColumnBase0 = new ColumnBase<ColumnMappingBase>("IdPedido", "int", restauranteSaborCaseroModelsPedidoTableBase);
            restauranteSaborCaseroModelsPedidoTableBase.Columns.Add("IdPedido", idPedidoColumnBase0);
            var tipoPedidoColumnBase = new ColumnBase<ColumnMappingBase>("TipoPedido", "int", restauranteSaborCaseroModelsPedidoTableBase);
            restauranteSaborCaseroModelsPedidoTableBase.Columns.Add("TipoPedido", tipoPedidoColumnBase);
            relationalModel.DefaultTables.Add("RestauranteSaborCasero.Models.Pedido", restauranteSaborCaseroModelsPedidoTableBase);
            var restauranteSaborCaseroModelsPedidoMappingBase = new TableMappingBase<ColumnMappingBase>(pedido, restauranteSaborCaseroModelsPedidoTableBase, true);
            restauranteSaborCaseroModelsPedidoTableBase.AddTypeMapping(restauranteSaborCaseroModelsPedidoMappingBase, false);
            defaultTableMappings5.Add(restauranteSaborCaseroModelsPedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idPedidoColumnBase0, pedido.FindProperty("IdPedido")!, restauranteSaborCaseroModelsPedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)estadoColumnBase1, pedido.FindProperty("Estado")!, restauranteSaborCaseroModelsPedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)fechaColumnBase1, pedido.FindProperty("Fecha")!, restauranteSaborCaseroModelsPedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)horaFinColumnBase, pedido.FindProperty("HoraFin")!, restauranteSaborCaseroModelsPedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)horaInicioColumnBase, pedido.FindProperty("HoraInicio")!, restauranteSaborCaseroModelsPedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idMesaColumnBase0, pedido.FindProperty("IdMesa")!, restauranteSaborCaseroModelsPedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idMeseroColumnBase, pedido.FindProperty("IdMesero")!, restauranteSaborCaseroModelsPedidoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tipoPedidoColumnBase, pedido.FindProperty("TipoPedido")!, restauranteSaborCaseroModelsPedidoMappingBase);

            var tableMappings5 = new List<TableMapping>();
            pedido.SetRuntimeAnnotation("Relational:TableMappings", tableMappings5);
            var pedidosTable = new Table("Pedidos", null, relationalModel);
            var idPedidoColumn0 = new Column("IdPedido", "int", pedidosTable);
            pedidosTable.Columns.Add("IdPedido", idPedidoColumn0);
            idPedidoColumn0.AddAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
            var estadoColumn1 = new Column("Estado", "int", pedidosTable);
            pedidosTable.Columns.Add("Estado", estadoColumn1);
            var fechaColumn1 = new Column("Fecha", "datetime(6)", pedidosTable);
            pedidosTable.Columns.Add("Fecha", fechaColumn1);
            var horaFinColumn = new Column("HoraFin", "time(6)", pedidosTable)
            {
                IsNullable = true
            };
            pedidosTable.Columns.Add("HoraFin", horaFinColumn);
            var horaInicioColumn = new Column("HoraInicio", "time(6)", pedidosTable);
            pedidosTable.Columns.Add("HoraInicio", horaInicioColumn);
            var idMesaColumn0 = new Column("IdMesa", "int", pedidosTable)
            {
                IsNullable = true
            };
            pedidosTable.Columns.Add("IdMesa", idMesaColumn0);
            var idMeseroColumn = new Column("IdMesero", "int", pedidosTable);
            pedidosTable.Columns.Add("IdMesero", idMeseroColumn);
            var tipoPedidoColumn = new Column("TipoPedido", "int", pedidosTable);
            pedidosTable.Columns.Add("TipoPedido", tipoPedidoColumn);
            var pK_Pedidos = new UniqueConstraint("PK_Pedidos", pedidosTable, new[] { idPedidoColumn0 });
            pedidosTable.PrimaryKey = pK_Pedidos;
            var pK_PedidosUc = RelationalModel.GetKey(this,
                "RestauranteSaborCasero.Models.Pedido",
                new[] { "IdPedido" });
            pK_Pedidos.MappedKeys.Add(pK_PedidosUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_PedidosUc).Add(pK_Pedidos);
            pedidosTable.UniqueConstraints.Add("PK_Pedidos", pK_Pedidos);
            var iX_Pedidos_IdMesa = new TableIndex(
            "IX_Pedidos_IdMesa", pedidosTable, new[] { idMesaColumn0 }, false);
            var iX_Pedidos_IdMesaIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.Pedido",
                new[] { "IdMesa" });
            iX_Pedidos_IdMesa.MappedIndexes.Add(iX_Pedidos_IdMesaIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Pedidos_IdMesaIx).Add(iX_Pedidos_IdMesa);
            pedidosTable.Indexes.Add("IX_Pedidos_IdMesa", iX_Pedidos_IdMesa);
            var iX_Pedidos_IdMesero = new TableIndex(
            "IX_Pedidos_IdMesero", pedidosTable, new[] { idMeseroColumn }, false);
            var iX_Pedidos_IdMeseroIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.Pedido",
                new[] { "IdMesero" });
            iX_Pedidos_IdMesero.MappedIndexes.Add(iX_Pedidos_IdMeseroIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Pedidos_IdMeseroIx).Add(iX_Pedidos_IdMesero);
            pedidosTable.Indexes.Add("IX_Pedidos_IdMesero", iX_Pedidos_IdMesero);
            pedidosTable.AddAnnotation("MySql:CharSet", "utf8mb4");
            relationalModel.Tables.Add(("Pedidos", null), pedidosTable);
            var pedidosTableMapping = new TableMapping(pedido, pedidosTable, true);
            pedidosTable.AddTypeMapping(pedidosTableMapping, false);
            tableMappings5.Add(pedidosTableMapping);
            RelationalModel.CreateColumnMapping(idPedidoColumn0, pedido.FindProperty("IdPedido")!, pedidosTableMapping);
            RelationalModel.CreateColumnMapping(estadoColumn1, pedido.FindProperty("Estado")!, pedidosTableMapping);
            RelationalModel.CreateColumnMapping(fechaColumn1, pedido.FindProperty("Fecha")!, pedidosTableMapping);
            RelationalModel.CreateColumnMapping(horaFinColumn, pedido.FindProperty("HoraFin")!, pedidosTableMapping);
            RelationalModel.CreateColumnMapping(horaInicioColumn, pedido.FindProperty("HoraInicio")!, pedidosTableMapping);
            RelationalModel.CreateColumnMapping(idMesaColumn0, pedido.FindProperty("IdMesa")!, pedidosTableMapping);
            RelationalModel.CreateColumnMapping(idMeseroColumn, pedido.FindProperty("IdMesero")!, pedidosTableMapping);
            RelationalModel.CreateColumnMapping(tipoPedidoColumn, pedido.FindProperty("TipoPedido")!, pedidosTableMapping);

            var plato = FindEntityType("RestauranteSaborCasero.Models.Plato")!;

            var defaultTableMappings6 = new List<TableMappingBase<ColumnMappingBase>>();
            plato.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings6);
            var restauranteSaborCaseroModelsPlatoTableBase = new TableBase("RestauranteSaborCasero.Models.Plato", null, relationalModel);
            var estadoColumnBase2 = new ColumnBase<ColumnMappingBase>("Estado", "int", restauranteSaborCaseroModelsPlatoTableBase);
            restauranteSaborCaseroModelsPlatoTableBase.Columns.Add("Estado", estadoColumnBase2);
            var idPlatoColumnBase0 = new ColumnBase<ColumnMappingBase>("IdPlato", "int", restauranteSaborCaseroModelsPlatoTableBase);
            restauranteSaborCaseroModelsPlatoTableBase.Columns.Add("IdPlato", idPlatoColumnBase0);
            var nombreColumnBase0 = new ColumnBase<ColumnMappingBase>("Nombre", "varchar(100)", restauranteSaborCaseroModelsPlatoTableBase);
            restauranteSaborCaseroModelsPlatoTableBase.Columns.Add("Nombre", nombreColumnBase0);
            var precioColumnBase = new ColumnBase<ColumnMappingBase>("Precio", "decimal(10,2)", restauranteSaborCaseroModelsPlatoTableBase);
            restauranteSaborCaseroModelsPlatoTableBase.Columns.Add("Precio", precioColumnBase);
            var tiempoEstimadoColumnBase = new ColumnBase<ColumnMappingBase>("TiempoEstimado", "int", restauranteSaborCaseroModelsPlatoTableBase);
            restauranteSaborCaseroModelsPlatoTableBase.Columns.Add("TiempoEstimado", tiempoEstimadoColumnBase);
            relationalModel.DefaultTables.Add("RestauranteSaborCasero.Models.Plato", restauranteSaborCaseroModelsPlatoTableBase);
            var restauranteSaborCaseroModelsPlatoMappingBase = new TableMappingBase<ColumnMappingBase>(plato, restauranteSaborCaseroModelsPlatoTableBase, true);
            restauranteSaborCaseroModelsPlatoTableBase.AddTypeMapping(restauranteSaborCaseroModelsPlatoMappingBase, false);
            defaultTableMappings6.Add(restauranteSaborCaseroModelsPlatoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idPlatoColumnBase0, plato.FindProperty("IdPlato")!, restauranteSaborCaseroModelsPlatoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)estadoColumnBase2, plato.FindProperty("Estado")!, restauranteSaborCaseroModelsPlatoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nombreColumnBase0, plato.FindProperty("Nombre")!, restauranteSaborCaseroModelsPlatoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)precioColumnBase, plato.FindProperty("Precio")!, restauranteSaborCaseroModelsPlatoMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)tiempoEstimadoColumnBase, plato.FindProperty("TiempoEstimado")!, restauranteSaborCaseroModelsPlatoMappingBase);

            var tableMappings6 = new List<TableMapping>();
            plato.SetRuntimeAnnotation("Relational:TableMappings", tableMappings6);
            var platosTable = new Table("Platos", null, relationalModel);
            var idPlatoColumn0 = new Column("IdPlato", "int", platosTable);
            platosTable.Columns.Add("IdPlato", idPlatoColumn0);
            idPlatoColumn0.AddAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
            var estadoColumn2 = new Column("Estado", "int", platosTable);
            platosTable.Columns.Add("Estado", estadoColumn2);
            var nombreColumn0 = new Column("Nombre", "varchar(100)", platosTable);
            platosTable.Columns.Add("Nombre", nombreColumn0);
            nombreColumn0.AddAnnotation("MySql:CharSet", "utf8mb4");
            var precioColumn = new Column("Precio", "decimal(10,2)", platosTable);
            platosTable.Columns.Add("Precio", precioColumn);
            var tiempoEstimadoColumn = new Column("TiempoEstimado", "int", platosTable);
            platosTable.Columns.Add("TiempoEstimado", tiempoEstimadoColumn);
            var pK_Platos = new UniqueConstraint("PK_Platos", platosTable, new[] { idPlatoColumn0 });
            platosTable.PrimaryKey = pK_Platos;
            var pK_PlatosUc = RelationalModel.GetKey(this,
                "RestauranteSaborCasero.Models.Plato",
                new[] { "IdPlato" });
            pK_Platos.MappedKeys.Add(pK_PlatosUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_PlatosUc).Add(pK_Platos);
            platosTable.UniqueConstraints.Add("PK_Platos", pK_Platos);
            platosTable.AddAnnotation("MySql:CharSet", "utf8mb4");
            relationalModel.Tables.Add(("Platos", null), platosTable);
            var platosTableMapping = new TableMapping(plato, platosTable, true);
            platosTable.AddTypeMapping(platosTableMapping, false);
            tableMappings6.Add(platosTableMapping);
            RelationalModel.CreateColumnMapping(idPlatoColumn0, plato.FindProperty("IdPlato")!, platosTableMapping);
            RelationalModel.CreateColumnMapping(estadoColumn2, plato.FindProperty("Estado")!, platosTableMapping);
            RelationalModel.CreateColumnMapping(nombreColumn0, plato.FindProperty("Nombre")!, platosTableMapping);
            RelationalModel.CreateColumnMapping(precioColumn, plato.FindProperty("Precio")!, platosTableMapping);
            RelationalModel.CreateColumnMapping(tiempoEstimadoColumn, plato.FindProperty("TiempoEstimado")!, platosTableMapping);

            var platoIngrediente = FindEntityType("RestauranteSaborCasero.Models.PlatoIngrediente")!;

            var defaultTableMappings7 = new List<TableMappingBase<ColumnMappingBase>>();
            platoIngrediente.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings7);
            var restauranteSaborCaseroModelsPlatoIngredienteTableBase = new TableBase("RestauranteSaborCasero.Models.PlatoIngrediente", null, relationalModel);
            var cantidadNecesariaColumnBase = new ColumnBase<ColumnMappingBase>("CantidadNecesaria", "decimal(10,2)", restauranteSaborCaseroModelsPlatoIngredienteTableBase);
            restauranteSaborCaseroModelsPlatoIngredienteTableBase.Columns.Add("CantidadNecesaria", cantidadNecesariaColumnBase);
            var idIngredienteColumnBase2 = new ColumnBase<ColumnMappingBase>("IdIngrediente", "int", restauranteSaborCaseroModelsPlatoIngredienteTableBase);
            restauranteSaborCaseroModelsPlatoIngredienteTableBase.Columns.Add("IdIngrediente", idIngredienteColumnBase2);
            var idPlatoColumnBase1 = new ColumnBase<ColumnMappingBase>("IdPlato", "int", restauranteSaborCaseroModelsPlatoIngredienteTableBase);
            restauranteSaborCaseroModelsPlatoIngredienteTableBase.Columns.Add("IdPlato", idPlatoColumnBase1);
            relationalModel.DefaultTables.Add("RestauranteSaborCasero.Models.PlatoIngrediente", restauranteSaborCaseroModelsPlatoIngredienteTableBase);
            var restauranteSaborCaseroModelsPlatoIngredienteMappingBase = new TableMappingBase<ColumnMappingBase>(platoIngrediente, restauranteSaborCaseroModelsPlatoIngredienteTableBase, true);
            restauranteSaborCaseroModelsPlatoIngredienteTableBase.AddTypeMapping(restauranteSaborCaseroModelsPlatoIngredienteMappingBase, false);
            defaultTableMappings7.Add(restauranteSaborCaseroModelsPlatoIngredienteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idIngredienteColumnBase2, platoIngrediente.FindProperty("IdIngrediente")!, restauranteSaborCaseroModelsPlatoIngredienteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idPlatoColumnBase1, platoIngrediente.FindProperty("IdPlato")!, restauranteSaborCaseroModelsPlatoIngredienteMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)cantidadNecesariaColumnBase, platoIngrediente.FindProperty("CantidadNecesaria")!, restauranteSaborCaseroModelsPlatoIngredienteMappingBase);

            var tableMappings7 = new List<TableMapping>();
            platoIngrediente.SetRuntimeAnnotation("Relational:TableMappings", tableMappings7);
            var platoIngredientesTable = new Table("PlatoIngredientes", null, relationalModel);
            var idPlatoColumn1 = new Column("IdPlato", "int", platoIngredientesTable);
            platoIngredientesTable.Columns.Add("IdPlato", idPlatoColumn1);
            var idIngredienteColumn2 = new Column("IdIngrediente", "int", platoIngredientesTable);
            platoIngredientesTable.Columns.Add("IdIngrediente", idIngredienteColumn2);
            var cantidadNecesariaColumn = new Column("CantidadNecesaria", "decimal(10,2)", platoIngredientesTable);
            platoIngredientesTable.Columns.Add("CantidadNecesaria", cantidadNecesariaColumn);
            var pK_PlatoIngredientes = new UniqueConstraint("PK_PlatoIngredientes", platoIngredientesTable, new[] { idPlatoColumn1, idIngredienteColumn2 });
            platoIngredientesTable.PrimaryKey = pK_PlatoIngredientes;
            var pK_PlatoIngredientesUc = RelationalModel.GetKey(this,
                "RestauranteSaborCasero.Models.PlatoIngrediente",
                new[] { "IdPlato", "IdIngrediente" });
            pK_PlatoIngredientes.MappedKeys.Add(pK_PlatoIngredientesUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_PlatoIngredientesUc).Add(pK_PlatoIngredientes);
            platoIngredientesTable.UniqueConstraints.Add("PK_PlatoIngredientes", pK_PlatoIngredientes);
            var iX_PlatoIngredientes_IdIngrediente = new TableIndex(
            "IX_PlatoIngredientes_IdIngrediente", platoIngredientesTable, new[] { idIngredienteColumn2 }, false);
            var iX_PlatoIngredientes_IdIngredienteIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.PlatoIngrediente",
                new[] { "IdIngrediente" });
            iX_PlatoIngredientes_IdIngrediente.MappedIndexes.Add(iX_PlatoIngredientes_IdIngredienteIx);
            RelationalModel.GetOrCreateTableIndexes(iX_PlatoIngredientes_IdIngredienteIx).Add(iX_PlatoIngredientes_IdIngrediente);
            platoIngredientesTable.Indexes.Add("IX_PlatoIngredientes_IdIngrediente", iX_PlatoIngredientes_IdIngrediente);
            platoIngredientesTable.AddAnnotation("MySql:CharSet", "utf8mb4");
            relationalModel.Tables.Add(("PlatoIngredientes", null), platoIngredientesTable);
            var platoIngredientesTableMapping = new TableMapping(platoIngrediente, platoIngredientesTable, true);
            platoIngredientesTable.AddTypeMapping(platoIngredientesTableMapping, false);
            tableMappings7.Add(platoIngredientesTableMapping);
            RelationalModel.CreateColumnMapping(idIngredienteColumn2, platoIngrediente.FindProperty("IdIngrediente")!, platoIngredientesTableMapping);
            RelationalModel.CreateColumnMapping(idPlatoColumn1, platoIngrediente.FindProperty("IdPlato")!, platoIngredientesTableMapping);
            RelationalModel.CreateColumnMapping(cantidadNecesariaColumn, platoIngrediente.FindProperty("CantidadNecesaria")!, platoIngredientesTableMapping);

            var usuario = FindEntityType("RestauranteSaborCasero.Models.Usuario")!;

            var defaultTableMappings8 = new List<TableMappingBase<ColumnMappingBase>>();
            usuario.SetRuntimeAnnotation("Relational:DefaultMappings", defaultTableMappings8);
            var restauranteSaborCaseroModelsUsuarioTableBase = new TableBase("RestauranteSaborCasero.Models.Usuario", null, relationalModel);
            var activoColumnBase = new ColumnBase<ColumnMappingBase>("Activo", "tinyint(1)", restauranteSaborCaseroModelsUsuarioTableBase);
            restauranteSaborCaseroModelsUsuarioTableBase.Columns.Add("Activo", activoColumnBase);
            var contrasenaHashColumnBase = new ColumnBase<ColumnMappingBase>("ContrasenaHash", "varchar(255)", restauranteSaborCaseroModelsUsuarioTableBase);
            restauranteSaborCaseroModelsUsuarioTableBase.Columns.Add("ContrasenaHash", contrasenaHashColumnBase);
            var correoColumnBase = new ColumnBase<ColumnMappingBase>("Correo", "varchar(150)", restauranteSaborCaseroModelsUsuarioTableBase);
            restauranteSaborCaseroModelsUsuarioTableBase.Columns.Add("Correo", correoColumnBase);
            var idUsuarioColumnBase0 = new ColumnBase<ColumnMappingBase>("IdUsuario", "int", restauranteSaborCaseroModelsUsuarioTableBase);
            restauranteSaborCaseroModelsUsuarioTableBase.Columns.Add("IdUsuario", idUsuarioColumnBase0);
            var nombreColumnBase1 = new ColumnBase<ColumnMappingBase>("Nombre", "varchar(100)", restauranteSaborCaseroModelsUsuarioTableBase);
            restauranteSaborCaseroModelsUsuarioTableBase.Columns.Add("Nombre", nombreColumnBase1);
            var rolColumnBase = new ColumnBase<ColumnMappingBase>("Rol", "int", restauranteSaborCaseroModelsUsuarioTableBase);
            restauranteSaborCaseroModelsUsuarioTableBase.Columns.Add("Rol", rolColumnBase);
            relationalModel.DefaultTables.Add("RestauranteSaborCasero.Models.Usuario", restauranteSaborCaseroModelsUsuarioTableBase);
            var restauranteSaborCaseroModelsUsuarioMappingBase = new TableMappingBase<ColumnMappingBase>(usuario, restauranteSaborCaseroModelsUsuarioTableBase, true);
            restauranteSaborCaseroModelsUsuarioTableBase.AddTypeMapping(restauranteSaborCaseroModelsUsuarioMappingBase, false);
            defaultTableMappings8.Add(restauranteSaborCaseroModelsUsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)idUsuarioColumnBase0, usuario.FindProperty("IdUsuario")!, restauranteSaborCaseroModelsUsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)activoColumnBase, usuario.FindProperty("Activo")!, restauranteSaborCaseroModelsUsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)contrasenaHashColumnBase, usuario.FindProperty("ContrasenaHash")!, restauranteSaborCaseroModelsUsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)correoColumnBase, usuario.FindProperty("Correo")!, restauranteSaborCaseroModelsUsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)nombreColumnBase1, usuario.FindProperty("Nombre")!, restauranteSaborCaseroModelsUsuarioMappingBase);
            RelationalModel.CreateColumnMapping((ColumnBase<ColumnMappingBase>)rolColumnBase, usuario.FindProperty("Rol")!, restauranteSaborCaseroModelsUsuarioMappingBase);

            var tableMappings8 = new List<TableMapping>();
            usuario.SetRuntimeAnnotation("Relational:TableMappings", tableMappings8);
            var usuariosTable = new Table("Usuarios", null, relationalModel);
            var idUsuarioColumn0 = new Column("IdUsuario", "int", usuariosTable);
            usuariosTable.Columns.Add("IdUsuario", idUsuarioColumn0);
            idUsuarioColumn0.AddAnnotation("MySql:ValueGenerationStrategy", MySqlValueGenerationStrategy.IdentityColumn);
            var activoColumn = new Column("Activo", "tinyint(1)", usuariosTable);
            usuariosTable.Columns.Add("Activo", activoColumn);
            var contrasenaHashColumn = new Column("ContrasenaHash", "varchar(255)", usuariosTable);
            usuariosTable.Columns.Add("ContrasenaHash", contrasenaHashColumn);
            contrasenaHashColumn.AddAnnotation("MySql:CharSet", "utf8mb4");
            var correoColumn = new Column("Correo", "varchar(150)", usuariosTable);
            usuariosTable.Columns.Add("Correo", correoColumn);
            correoColumn.AddAnnotation("MySql:CharSet", "utf8mb4");
            var nombreColumn1 = new Column("Nombre", "varchar(100)", usuariosTable);
            usuariosTable.Columns.Add("Nombre", nombreColumn1);
            nombreColumn1.AddAnnotation("MySql:CharSet", "utf8mb4");
            var rolColumn = new Column("Rol", "int", usuariosTable);
            usuariosTable.Columns.Add("Rol", rolColumn);
            var pK_Usuarios = new UniqueConstraint("PK_Usuarios", usuariosTable, new[] { idUsuarioColumn0 });
            usuariosTable.PrimaryKey = pK_Usuarios;
            var pK_UsuariosUc = RelationalModel.GetKey(this,
                "RestauranteSaborCasero.Models.Usuario",
                new[] { "IdUsuario" });
            pK_Usuarios.MappedKeys.Add(pK_UsuariosUc);
            RelationalModel.GetOrCreateUniqueConstraints(pK_UsuariosUc).Add(pK_Usuarios);
            usuariosTable.UniqueConstraints.Add("PK_Usuarios", pK_Usuarios);
            var iX_Usuarios_Correo = new TableIndex(
            "IX_Usuarios_Correo", usuariosTable, new[] { correoColumn }, true);
            var iX_Usuarios_CorreoIx = RelationalModel.GetIndex(this,
                "RestauranteSaborCasero.Models.Usuario",
                new[] { "Correo" });
            iX_Usuarios_Correo.MappedIndexes.Add(iX_Usuarios_CorreoIx);
            RelationalModel.GetOrCreateTableIndexes(iX_Usuarios_CorreoIx).Add(iX_Usuarios_Correo);
            usuariosTable.Indexes.Add("IX_Usuarios_Correo", iX_Usuarios_Correo);
            usuariosTable.AddAnnotation("MySql:CharSet", "utf8mb4");
            relationalModel.Tables.Add(("Usuarios", null), usuariosTable);
            var usuariosTableMapping = new TableMapping(usuario, usuariosTable, true);
            usuariosTable.AddTypeMapping(usuariosTableMapping, false);
            tableMappings8.Add(usuariosTableMapping);
            RelationalModel.CreateColumnMapping(idUsuarioColumn0, usuario.FindProperty("IdUsuario")!, usuariosTableMapping);
            RelationalModel.CreateColumnMapping(activoColumn, usuario.FindProperty("Activo")!, usuariosTableMapping);
            RelationalModel.CreateColumnMapping(contrasenaHashColumn, usuario.FindProperty("ContrasenaHash")!, usuariosTableMapping);
            RelationalModel.CreateColumnMapping(correoColumn, usuario.FindProperty("Correo")!, usuariosTableMapping);
            RelationalModel.CreateColumnMapping(nombreColumn1, usuario.FindProperty("Nombre")!, usuariosTableMapping);
            RelationalModel.CreateColumnMapping(rolColumn, usuario.FindProperty("Rol")!, usuariosTableMapping);
            var fK_Compras_Usuarios_IdUsuario = new ForeignKeyConstraint(
                "FK_Compras_Usuarios_IdUsuario", comprasTable, usuariosTable,
                new[] { idUsuarioColumn },
                usuariosTable.FindUniqueConstraint("PK_Usuarios")!, ReferentialAction.Restrict);
            var fK_Compras_Usuarios_IdUsuarioFk = RelationalModel.GetForeignKey(this,
                "RestauranteSaborCasero.Models.Compra",
                new[] { "IdUsuario" },
                "RestauranteSaborCasero.Models.Usuario",
                new[] { "IdUsuario" });
            fK_Compras_Usuarios_IdUsuario.MappedForeignKeys.Add(fK_Compras_Usuarios_IdUsuarioFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Compras_Usuarios_IdUsuarioFk).Add(fK_Compras_Usuarios_IdUsuario);
            comprasTable.ForeignKeyConstraints.Add(fK_Compras_Usuarios_IdUsuario);
            usuariosTable.ReferencingForeignKeyConstraints.Add(fK_Compras_Usuarios_IdUsuario);
            var fK_DetalleCompras_Compras_IdCompra = new ForeignKeyConstraint(
                "FK_DetalleCompras_Compras_IdCompra", detalleComprasTable, comprasTable,
                new[] { idCompraColumn0 },
                comprasTable.FindUniqueConstraint("PK_Compras")!, ReferentialAction.Cascade);
            var fK_DetalleCompras_Compras_IdCompraFk = RelationalModel.GetForeignKey(this,
                "RestauranteSaborCasero.Models.DetalleCompra",
                new[] { "IdCompra" },
                "RestauranteSaborCasero.Models.Compra",
                new[] { "IdCompra" });
            fK_DetalleCompras_Compras_IdCompra.MappedForeignKeys.Add(fK_DetalleCompras_Compras_IdCompraFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_DetalleCompras_Compras_IdCompraFk).Add(fK_DetalleCompras_Compras_IdCompra);
            detalleComprasTable.ForeignKeyConstraints.Add(fK_DetalleCompras_Compras_IdCompra);
            comprasTable.ReferencingForeignKeyConstraints.Add(fK_DetalleCompras_Compras_IdCompra);
            var fK_DetalleCompras_Ingredientes_IdIngrediente = new ForeignKeyConstraint(
                "FK_DetalleCompras_Ingredientes_IdIngrediente", detalleComprasTable, ingredientesTable,
                new[] { idIngredienteColumn },
                ingredientesTable.FindUniqueConstraint("PK_Ingredientes")!, ReferentialAction.Restrict);
            var fK_DetalleCompras_Ingredientes_IdIngredienteFk = RelationalModel.GetForeignKey(this,
                "RestauranteSaborCasero.Models.DetalleCompra",
                new[] { "IdIngrediente" },
                "RestauranteSaborCasero.Models.Ingrediente",
                new[] { "IdIngrediente" });
            fK_DetalleCompras_Ingredientes_IdIngrediente.MappedForeignKeys.Add(fK_DetalleCompras_Ingredientes_IdIngredienteFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_DetalleCompras_Ingredientes_IdIngredienteFk).Add(fK_DetalleCompras_Ingredientes_IdIngrediente);
            detalleComprasTable.ForeignKeyConstraints.Add(fK_DetalleCompras_Ingredientes_IdIngrediente);
            ingredientesTable.ReferencingForeignKeyConstraints.Add(fK_DetalleCompras_Ingredientes_IdIngrediente);
            var fK_DetallePedidos_Pedidos_IdPedido = new ForeignKeyConstraint(
                "FK_DetallePedidos_Pedidos_IdPedido", detallePedidosTable, pedidosTable,
                new[] { idPedidoColumn },
                pedidosTable.FindUniqueConstraint("PK_Pedidos")!, ReferentialAction.Cascade);
            var fK_DetallePedidos_Pedidos_IdPedidoFk = RelationalModel.GetForeignKey(this,
                "RestauranteSaborCasero.Models.DetallePedido",
                new[] { "IdPedido" },
                "RestauranteSaborCasero.Models.Pedido",
                new[] { "IdPedido" });
            fK_DetallePedidos_Pedidos_IdPedido.MappedForeignKeys.Add(fK_DetallePedidos_Pedidos_IdPedidoFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_DetallePedidos_Pedidos_IdPedidoFk).Add(fK_DetallePedidos_Pedidos_IdPedido);
            detallePedidosTable.ForeignKeyConstraints.Add(fK_DetallePedidos_Pedidos_IdPedido);
            pedidosTable.ReferencingForeignKeyConstraints.Add(fK_DetallePedidos_Pedidos_IdPedido);
            var fK_DetallePedidos_Platos_IdPlato = new ForeignKeyConstraint(
                "FK_DetallePedidos_Platos_IdPlato", detallePedidosTable, platosTable,
                new[] { idPlatoColumn },
                platosTable.FindUniqueConstraint("PK_Platos")!, ReferentialAction.Restrict);
            var fK_DetallePedidos_Platos_IdPlatoFk = RelationalModel.GetForeignKey(this,
                "RestauranteSaborCasero.Models.DetallePedido",
                new[] { "IdPlato" },
                "RestauranteSaborCasero.Models.Plato",
                new[] { "IdPlato" });
            fK_DetallePedidos_Platos_IdPlato.MappedForeignKeys.Add(fK_DetallePedidos_Platos_IdPlatoFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_DetallePedidos_Platos_IdPlatoFk).Add(fK_DetallePedidos_Platos_IdPlato);
            detallePedidosTable.ForeignKeyConstraints.Add(fK_DetallePedidos_Platos_IdPlato);
            platosTable.ReferencingForeignKeyConstraints.Add(fK_DetallePedidos_Platos_IdPlato);
            var fK_Inventarios_Ingredientes_IdIngrediente = new ForeignKeyConstraint(
                "FK_Inventarios_Ingredientes_IdIngrediente", inventariosTable, ingredientesTable,
                new[] { idIngredienteColumn1 },
                ingredientesTable.FindUniqueConstraint("PK_Ingredientes")!, ReferentialAction.Restrict);
            var fK_Inventarios_Ingredientes_IdIngredienteFk = RelationalModel.GetForeignKey(this,
                "RestauranteSaborCasero.Models.Inventario",
                new[] { "IdIngrediente" },
                "RestauranteSaborCasero.Models.Ingrediente",
                new[] { "IdIngrediente" });
            fK_Inventarios_Ingredientes_IdIngrediente.MappedForeignKeys.Add(fK_Inventarios_Ingredientes_IdIngredienteFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Inventarios_Ingredientes_IdIngredienteFk).Add(fK_Inventarios_Ingredientes_IdIngrediente);
            inventariosTable.ForeignKeyConstraints.Add(fK_Inventarios_Ingredientes_IdIngrediente);
            ingredientesTable.ReferencingForeignKeyConstraints.Add(fK_Inventarios_Ingredientes_IdIngrediente);
            var fK_Pedidos_Mesas_IdMesa = new ForeignKeyConstraint(
                "FK_Pedidos_Mesas_IdMesa", pedidosTable, mesasTable,
                new[] { idMesaColumn0 },
                mesasTable.FindUniqueConstraint("PK_Mesas")!, ReferentialAction.SetNull);
            var fK_Pedidos_Mesas_IdMesaFk = RelationalModel.GetForeignKey(this,
                "RestauranteSaborCasero.Models.Pedido",
                new[] { "IdMesa" },
                "RestauranteSaborCasero.Models.Mesa",
                new[] { "IdMesa" });
            fK_Pedidos_Mesas_IdMesa.MappedForeignKeys.Add(fK_Pedidos_Mesas_IdMesaFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Pedidos_Mesas_IdMesaFk).Add(fK_Pedidos_Mesas_IdMesa);
            pedidosTable.ForeignKeyConstraints.Add(fK_Pedidos_Mesas_IdMesa);
            mesasTable.ReferencingForeignKeyConstraints.Add(fK_Pedidos_Mesas_IdMesa);
            var fK_Pedidos_Usuarios_IdMesero = new ForeignKeyConstraint(
                "FK_Pedidos_Usuarios_IdMesero", pedidosTable, usuariosTable,
                new[] { idMeseroColumn },
                usuariosTable.FindUniqueConstraint("PK_Usuarios")!, ReferentialAction.Restrict);
            var fK_Pedidos_Usuarios_IdMeseroFk = RelationalModel.GetForeignKey(this,
                "RestauranteSaborCasero.Models.Pedido",
                new[] { "IdMesero" },
                "RestauranteSaborCasero.Models.Usuario",
                new[] { "IdUsuario" });
            fK_Pedidos_Usuarios_IdMesero.MappedForeignKeys.Add(fK_Pedidos_Usuarios_IdMeseroFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_Pedidos_Usuarios_IdMeseroFk).Add(fK_Pedidos_Usuarios_IdMesero);
            pedidosTable.ForeignKeyConstraints.Add(fK_Pedidos_Usuarios_IdMesero);
            usuariosTable.ReferencingForeignKeyConstraints.Add(fK_Pedidos_Usuarios_IdMesero);
            var fK_PlatoIngredientes_Ingredientes_IdIngrediente = new ForeignKeyConstraint(
                "FK_PlatoIngredientes_Ingredientes_IdIngrediente", platoIngredientesTable, ingredientesTable,
                new[] { idIngredienteColumn2 },
                ingredientesTable.FindUniqueConstraint("PK_Ingredientes")!, ReferentialAction.Cascade);
            var fK_PlatoIngredientes_Ingredientes_IdIngredienteFk = RelationalModel.GetForeignKey(this,
                "RestauranteSaborCasero.Models.PlatoIngrediente",
                new[] { "IdIngrediente" },
                "RestauranteSaborCasero.Models.Ingrediente",
                new[] { "IdIngrediente" });
            fK_PlatoIngredientes_Ingredientes_IdIngrediente.MappedForeignKeys.Add(fK_PlatoIngredientes_Ingredientes_IdIngredienteFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_PlatoIngredientes_Ingredientes_IdIngredienteFk).Add(fK_PlatoIngredientes_Ingredientes_IdIngrediente);
            platoIngredientesTable.ForeignKeyConstraints.Add(fK_PlatoIngredientes_Ingredientes_IdIngrediente);
            ingredientesTable.ReferencingForeignKeyConstraints.Add(fK_PlatoIngredientes_Ingredientes_IdIngrediente);
            var fK_PlatoIngredientes_Platos_IdPlato = new ForeignKeyConstraint(
                "FK_PlatoIngredientes_Platos_IdPlato", platoIngredientesTable, platosTable,
                new[] { idPlatoColumn1 },
                platosTable.FindUniqueConstraint("PK_Platos")!, ReferentialAction.Cascade);
            var fK_PlatoIngredientes_Platos_IdPlatoFk = RelationalModel.GetForeignKey(this,
                "RestauranteSaborCasero.Models.PlatoIngrediente",
                new[] { "IdPlato" },
                "RestauranteSaborCasero.Models.Plato",
                new[] { "IdPlato" });
            fK_PlatoIngredientes_Platos_IdPlato.MappedForeignKeys.Add(fK_PlatoIngredientes_Platos_IdPlatoFk);
            RelationalModel.GetOrCreateForeignKeyConstraints(fK_PlatoIngredientes_Platos_IdPlatoFk).Add(fK_PlatoIngredientes_Platos_IdPlato);
            platoIngredientesTable.ForeignKeyConstraints.Add(fK_PlatoIngredientes_Platos_IdPlato);
            platosTable.ReferencingForeignKeyConstraints.Add(fK_PlatoIngredientes_Platos_IdPlato);
            relationalModel.AddAnnotation("MySql:CharSet", "utf8mb4");
            return relationalModel.MakeReadOnly();
        }
    }
}
