// <auto-generated />
using System;
using System.Reflection;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pomelo.EntityFrameworkCore.MySql.Storage.Internal;
using RestauranteSaborCasero.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace proyecto_final.RestauranteSaborCasero.Data.CompiledModels
{
    internal partial class MesaEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "RestauranteSaborCasero.Models.Mesa",
                typeof(Mesa),
                baseEntityType);

            var idMesa = runtimeEntityType.AddProperty(
                "IdMesa",
                typeof(int),
                propertyInfo: typeof(Mesa).GetProperty("IdMesa", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Mesa).GetField("<IdMesa>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            idMesa.TypeMapping = MySqlIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                keyComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v));

            var estado = runtimeEntityType.AddProperty(
                "Estado",
                typeof(EstadoMesa),
                propertyInfo: typeof(Mesa).GetProperty("Estado", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Mesa).GetField("<Estado>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            estado.TypeMapping = MySqlIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<EstadoMesa>(
                    (EstadoMesa v1, EstadoMesa v2) => object.Equals((object)v1, (object)v2),
                    (EstadoMesa v) => v.GetHashCode(),
                    (EstadoMesa v) => v),
                keyComparer: new ValueComparer<EstadoMesa>(
                    (EstadoMesa v1, EstadoMesa v2) => object.Equals((object)v1, (object)v2),
                    (EstadoMesa v) => v.GetHashCode(),
                    (EstadoMesa v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                converter: new ValueConverter<EstadoMesa, int>(
                    (EstadoMesa value) => (int)value,
                    (int value) => (EstadoMesa)value),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<EstadoMesa, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<EstadoMesa, int>(
                        (EstadoMesa value) => (int)value,
                        (int value) => (EstadoMesa)value)));
            estado.SetSentinelFromProviderValue(0);

            var numeroMesa = runtimeEntityType.AddProperty(
                "NumeroMesa",
                typeof(int),
                propertyInfo: typeof(Mesa).GetProperty("NumeroMesa", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Mesa).GetField("<NumeroMesa>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            numeroMesa.TypeMapping = MySqlIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                keyComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v));

            var key = runtimeEntityType.AddKey(
                new[] { idMesa });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { numeroMesa },
                unique: true);

            return runtimeEntityType;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Mesas");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
