// <auto-generated />
using System;
using System.Collections.Generic;
using System.Reflection;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.ChangeTracking;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Json;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pomelo.EntityFrameworkCore.MySql.Storage.Internal;
using RestauranteSaborCasero.Models;

#pragma warning disable 219, 612, 618
#nullable disable

namespace proyecto_final.RestauranteSaborCasero.Data.CompiledModels
{
    internal partial class PedidoEntityType
    {
        public static RuntimeEntityType Create(RuntimeModel model, RuntimeEntityType baseEntityType = null)
        {
            var runtimeEntityType = model.AddEntityType(
                "RestauranteSaborCasero.Models.Pedido",
                typeof(Pedido),
                baseEntityType);

            var idPedido = runtimeEntityType.AddProperty(
                "IdPedido",
                typeof(int),
                propertyInfo: typeof(Pedido).GetProperty("IdPedido", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Pedido).GetField("<IdPedido>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                valueGenerated: ValueGenerated.OnAdd,
                afterSaveBehavior: PropertySaveBehavior.Throw,
                sentinel: 0);
            idPedido.TypeMapping = MySqlIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                keyComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v));

            var estado = runtimeEntityType.AddProperty(
                "Estado",
                typeof(EstadoPedido),
                propertyInfo: typeof(Pedido).GetProperty("Estado", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Pedido).GetField("<Estado>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            estado.TypeMapping = MySqlIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<EstadoPedido>(
                    (EstadoPedido v1, EstadoPedido v2) => object.Equals((object)v1, (object)v2),
                    (EstadoPedido v) => v.GetHashCode(),
                    (EstadoPedido v) => v),
                keyComparer: new ValueComparer<EstadoPedido>(
                    (EstadoPedido v1, EstadoPedido v2) => object.Equals((object)v1, (object)v2),
                    (EstadoPedido v) => v.GetHashCode(),
                    (EstadoPedido v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                converter: new ValueConverter<EstadoPedido, int>(
                    (EstadoPedido value) => (int)value,
                    (int value) => (EstadoPedido)value),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<EstadoPedido, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<EstadoPedido, int>(
                        (EstadoPedido value) => (int)value,
                        (int value) => (EstadoPedido)value)));
            estado.SetSentinelFromProviderValue(0);

            var fecha = runtimeEntityType.AddProperty(
                "Fecha",
                typeof(DateTime),
                propertyInfo: typeof(Pedido).GetProperty("Fecha", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Pedido).GetField("<Fecha>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified));
            fecha.TypeMapping = MySqlDateTimeTypeMapping.Default.Clone(
                comparer: new ValueComparer<DateTime>(
                    (DateTime v1, DateTime v2) => v1.Equals(v2),
                    (DateTime v) => v.GetHashCode(),
                    (DateTime v) => v),
                keyComparer: new ValueComparer<DateTime>(
                    (DateTime v1, DateTime v2) => v1.Equals(v2),
                    (DateTime v) => v.GetHashCode(),
                    (DateTime v) => v),
                providerValueComparer: new ValueComparer<DateTime>(
                    (DateTime v1, DateTime v2) => v1.Equals(v2),
                    (DateTime v) => v.GetHashCode(),
                    (DateTime v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "datetime(6)",
                    precision: 6));

            var horaFin = runtimeEntityType.AddProperty(
                "HoraFin",
                typeof(TimeSpan?),
                propertyInfo: typeof(Pedido).GetProperty("HoraFin", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Pedido).GetField("<HoraFin>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            horaFin.TypeMapping = MySqlTimeTypeMapping.Default.Clone(
                comparer: new ValueComparer<TimeSpan?>(
                    (Nullable<TimeSpan> v1, Nullable<TimeSpan> v2) => v1.HasValue && v2.HasValue && (TimeSpan)v1 == (TimeSpan)v2 || !v1.HasValue && !v2.HasValue,
                    (Nullable<TimeSpan> v) => v.HasValue ? ((TimeSpan)v).GetHashCode() : 0,
                    (Nullable<TimeSpan> v) => v.HasValue ? (Nullable<TimeSpan>)(TimeSpan)v : default(Nullable<TimeSpan>)),
                keyComparer: new ValueComparer<TimeSpan?>(
                    (Nullable<TimeSpan> v1, Nullable<TimeSpan> v2) => v1.HasValue && v2.HasValue && (TimeSpan)v1 == (TimeSpan)v2 || !v1.HasValue && !v2.HasValue,
                    (Nullable<TimeSpan> v) => v.HasValue ? ((TimeSpan)v).GetHashCode() : 0,
                    (Nullable<TimeSpan> v) => v.HasValue ? (Nullable<TimeSpan>)(TimeSpan)v : default(Nullable<TimeSpan>)),
                providerValueComparer: new ValueComparer<TimeSpan?>(
                    (Nullable<TimeSpan> v1, Nullable<TimeSpan> v2) => v1.HasValue && v2.HasValue && (TimeSpan)v1 == (TimeSpan)v2 || !v1.HasValue && !v2.HasValue,
                    (Nullable<TimeSpan> v) => v.HasValue ? ((TimeSpan)v).GetHashCode() : 0,
                    (Nullable<TimeSpan> v) => v.HasValue ? (Nullable<TimeSpan>)(TimeSpan)v : default(Nullable<TimeSpan>)),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "time(6)",
                    precision: 6),
                clrType: typeof(TimeSpan));

            var horaInicio = runtimeEntityType.AddProperty(
                "HoraInicio",
                typeof(TimeSpan),
                propertyInfo: typeof(Pedido).GetProperty("HoraInicio", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Pedido).GetField("<HoraInicio>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: new TimeSpan(0, 0, 0, 0, 0));
            horaInicio.TypeMapping = MySqlTimeTypeMapping.Default.Clone(
                comparer: new ValueComparer<TimeSpan>(
                    (TimeSpan v1, TimeSpan v2) => v1.Equals(v2),
                    (TimeSpan v) => v.GetHashCode(),
                    (TimeSpan v) => v),
                keyComparer: new ValueComparer<TimeSpan>(
                    (TimeSpan v1, TimeSpan v2) => v1.Equals(v2),
                    (TimeSpan v) => v.GetHashCode(),
                    (TimeSpan v) => v),
                providerValueComparer: new ValueComparer<TimeSpan>(
                    (TimeSpan v1, TimeSpan v2) => v1.Equals(v2),
                    (TimeSpan v) => v.GetHashCode(),
                    (TimeSpan v) => v),
                mappingInfo: new RelationalTypeMappingInfo(
                    storeTypeName: "time(6)",
                    precision: 6),
                clrType: typeof(TimeSpan));

            var idMesa = runtimeEntityType.AddProperty(
                "IdMesa",
                typeof(int?),
                propertyInfo: typeof(Pedido).GetProperty("IdMesa", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Pedido).GetField("<IdMesa>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                nullable: true);
            idMesa.TypeMapping = MySqlIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int?>(
                    (Nullable<int> v1, Nullable<int> v2) => v1.HasValue && v2.HasValue && (int)v1 == (int)v2 || !v1.HasValue && !v2.HasValue,
                    (Nullable<int> v) => v.HasValue ? (int)v : 0,
                    (Nullable<int> v) => v.HasValue ? (Nullable<int>)(int)v : default(Nullable<int>)),
                keyComparer: new ValueComparer<int?>(
                    (Nullable<int> v1, Nullable<int> v2) => v1.HasValue && v2.HasValue && (int)v1 == (int)v2 || !v1.HasValue && !v2.HasValue,
                    (Nullable<int> v) => v.HasValue ? (int)v : 0,
                    (Nullable<int> v) => v.HasValue ? (Nullable<int>)(int)v : default(Nullable<int>)),
                providerValueComparer: new ValueComparer<int?>(
                    (Nullable<int> v1, Nullable<int> v2) => v1.HasValue && v2.HasValue && (int)v1 == (int)v2 || !v1.HasValue && !v2.HasValue,
                    (Nullable<int> v) => v.HasValue ? (int)v : 0,
                    (Nullable<int> v) => v.HasValue ? (Nullable<int>)(int)v : default(Nullable<int>)));

            var idMesero = runtimeEntityType.AddProperty(
                "IdMesero",
                typeof(int),
                propertyInfo: typeof(Pedido).GetProperty("IdMesero", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Pedido).GetField("<IdMesero>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                sentinel: 0);
            idMesero.TypeMapping = MySqlIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                keyComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v));

            var tipoPedido = runtimeEntityType.AddProperty(
                "TipoPedido",
                typeof(TipoPedido),
                propertyInfo: typeof(Pedido).GetProperty("TipoPedido", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Pedido).GetField("<TipoPedido>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));
            tipoPedido.TypeMapping = MySqlIntTypeMapping.Default.Clone(
                comparer: new ValueComparer<TipoPedido>(
                    (TipoPedido v1, TipoPedido v2) => object.Equals((object)v1, (object)v2),
                    (TipoPedido v) => v.GetHashCode(),
                    (TipoPedido v) => v),
                keyComparer: new ValueComparer<TipoPedido>(
                    (TipoPedido v1, TipoPedido v2) => object.Equals((object)v1, (object)v2),
                    (TipoPedido v) => v.GetHashCode(),
                    (TipoPedido v) => v),
                providerValueComparer: new ValueComparer<int>(
                    (int v1, int v2) => v1 == v2,
                    (int v) => v,
                    (int v) => v),
                converter: new ValueConverter<TipoPedido, int>(
                    (TipoPedido value) => (int)value,
                    (int value) => (TipoPedido)value),
                jsonValueReaderWriter: new JsonConvertedValueReaderWriter<TipoPedido, int>(
                    JsonInt32ReaderWriter.Instance,
                    new ValueConverter<TipoPedido, int>(
                        (TipoPedido value) => (int)value,
                        (int value) => (TipoPedido)value)));
            tipoPedido.SetSentinelFromProviderValue(0);

            var key = runtimeEntityType.AddKey(
                new[] { idPedido });
            runtimeEntityType.SetPrimaryKey(key);

            var index = runtimeEntityType.AddIndex(
                new[] { idMesa });

            var index0 = runtimeEntityType.AddIndex(
                new[] { idMesero });

            return runtimeEntityType;
        }

        public static RuntimeForeignKey CreateForeignKey1(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("IdMesa") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("IdMesa") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.SetNull);

            var mesa = declaringEntityType.AddNavigation("Mesa",
                runtimeForeignKey,
                onDependent: true,
                typeof(Mesa),
                propertyInfo: typeof(Pedido).GetProperty("Mesa", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Pedido).GetField("<Mesa>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var pedidos = principalEntityType.AddNavigation("Pedidos",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<Pedido>),
                propertyInfo: typeof(Mesa).GetProperty("Pedidos", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Mesa).GetField("<Pedidos>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static RuntimeForeignKey CreateForeignKey2(RuntimeEntityType declaringEntityType, RuntimeEntityType principalEntityType)
        {
            var runtimeForeignKey = declaringEntityType.AddForeignKey(new[] { declaringEntityType.FindProperty("IdMesero") },
                principalEntityType.FindKey(new[] { principalEntityType.FindProperty("IdUsuario") }),
                principalEntityType,
                deleteBehavior: DeleteBehavior.Restrict,
                required: true);

            var usuario = declaringEntityType.AddNavigation("Usuario",
                runtimeForeignKey,
                onDependent: true,
                typeof(Usuario),
                propertyInfo: typeof(Pedido).GetProperty("Usuario", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Pedido).GetField("<Usuario>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            var pedidos = principalEntityType.AddNavigation("Pedidos",
                runtimeForeignKey,
                onDependent: false,
                typeof(ICollection<Pedido>),
                propertyInfo: typeof(Usuario).GetProperty("Pedidos", BindingFlags.Public | BindingFlags.Instance | BindingFlags.DeclaredOnly),
                fieldInfo: typeof(Usuario).GetField("<Pedidos>k__BackingField", BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.DeclaredOnly));

            return runtimeForeignKey;
        }

        public static void CreateAnnotations(RuntimeEntityType runtimeEntityType)
        {
            runtimeEntityType.AddAnnotation("Relational:FunctionName", null);
            runtimeEntityType.AddAnnotation("Relational:Schema", null);
            runtimeEntityType.AddAnnotation("Relational:SqlQuery", null);
            runtimeEntityType.AddAnnotation("Relational:TableName", "Pedidos");
            runtimeEntityType.AddAnnotation("Relational:ViewName", null);
            runtimeEntityType.AddAnnotation("Relational:ViewSchema", null);

            Customize(runtimeEntityType);
        }

        static partial void Customize(RuntimeEntityType runtimeEntityType);
    }
}
