// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RestauranteSaborCasero.Data;

#nullable disable

namespace proyecto_final.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("RestauranteSaborCasero.Models.Compra", b =>
                {
                    b.Property<int>("IdCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Proveedor")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.HasKey("IdCompra");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Compras", (string)null);
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.DetalleCompra", b =>
                {
                    b.Property<int>("IdDetalleCompra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("IdCompra")
                        .HasColumnType("int");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int");

                    b.HasKey("IdDetalleCompra");

                    b.HasIndex("IdCompra");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("DetalleCompras", (string)null);
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.DetallePedido", b =>
                {
                    b.Property<int>("IdDetalle")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Cantidad")
                        .HasColumnType("int");

                    b.Property<int>("IdPedido")
                        .HasColumnType("int");

                    b.Property<int>("IdPlato")
                        .HasColumnType("int");

                    b.Property<string>("IndicacionesExtra")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdDetalle");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdPlato");

                    b.ToTable("DetallePedidos", (string)null);
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Ingrediente", b =>
                {
                    b.Property<int>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadDisponible")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("CantidadMinima")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("UnidadMedida")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)");

                    b.HasKey("IdIngrediente");

                    b.ToTable("Ingredientes", (string)null);
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Inventario", b =>
                {
                    b.Property<int>("IdInventario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("Cantidad")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int");

                    b.Property<string>("Motivo")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<int>("TipoMovimiento")
                        .HasColumnType("int");

                    b.HasKey("IdInventario");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("Inventarios", (string)null);
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Mesa", b =>
                {
                    b.Property<int>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<int>("NumeroMesa")
                        .HasColumnType("int");

                    b.HasKey("IdMesa");

                    b.HasIndex("NumeroMesa")
                        .IsUnique();

                    b.ToTable("Mesas", (string)null);
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Pedido", b =>
                {
                    b.Property<int>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime(6)");

                    b.Property<TimeSpan?>("HoraFin")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time(6)");

                    b.Property<int?>("IdMesa")
                        .HasColumnType("int");

                    b.Property<int>("IdMesero")
                        .HasColumnType("int");

                    b.Property<int>("TipoPedido")
                        .HasColumnType("int");

                    b.HasKey("IdPedido");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdMesero");

                    b.ToTable("Pedidos", (string)null);
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Plato", b =>
                {
                    b.Property<int>("IdPlato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal>("Precio")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TiempoEstimado")
                        .HasColumnType("int");

                    b.HasKey("IdPlato");

                    b.ToTable("Platos", (string)null);
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.PlatoIngrediente", b =>
                {
                    b.Property<int>("IdPlato")
                        .HasColumnType("int");

                    b.Property<int>("IdIngrediente")
                        .HasColumnType("int");

                    b.Property<decimal>("CantidadNecesaria")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdPlato", "IdIngrediente");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("PlatoIngredientes", (string)null);
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Activo")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ContrasenaHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Compra", b =>
                {
                    b.HasOne("RestauranteSaborCasero.Models.Usuario", "Usuario")
                        .WithMany("Compras")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.DetalleCompra", b =>
                {
                    b.HasOne("RestauranteSaborCasero.Models.Compra", "Compra")
                        .WithMany("Detalles")
                        .HasForeignKey("IdCompra")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteSaborCasero.Models.Ingrediente", "Ingrediente")
                        .WithMany("DetallesCompra")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Compra");

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.DetallePedido", b =>
                {
                    b.HasOne("RestauranteSaborCasero.Models.Pedido", "Pedido")
                        .WithMany("Detalles")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteSaborCasero.Models.Plato", "Plato")
                        .WithMany("DetallesPedido")
                        .HasForeignKey("IdPlato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Pedido");

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Inventario", b =>
                {
                    b.HasOne("RestauranteSaborCasero.Models.Ingrediente", "Ingrediente")
                        .WithMany("Inventarios")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ingrediente");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Pedido", b =>
                {
                    b.HasOne("RestauranteSaborCasero.Models.Mesa", "Mesa")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("RestauranteSaborCasero.Models.Usuario", "Usuario")
                        .WithMany("Pedidos")
                        .HasForeignKey("IdMesero")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Mesa");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.PlatoIngrediente", b =>
                {
                    b.HasOne("RestauranteSaborCasero.Models.Ingrediente", "Ingrediente")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RestauranteSaborCasero.Models.Plato", "Plato")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("IdPlato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Compra", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Ingrediente", b =>
                {
                    b.Navigation("DetallesCompra");

                    b.Navigation("Inventarios");

                    b.Navigation("PlatoIngredientes");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Mesa", b =>
                {
                    b.Navigation("Pedidos");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Pedido", b =>
                {
                    b.Navigation("Detalles");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Plato", b =>
                {
                    b.Navigation("DetallesPedido");

                    b.Navigation("PlatoIngredientes");
                });

            modelBuilder.Entity("RestauranteSaborCasero.Models.Usuario", b =>
                {
                    b.Navigation("Compras");

                    b.Navigation("Pedidos");
                });
#pragma warning restore 612, 618
        }
    }
}
